### ISSUE TITLE
Submit Button does not honour colors in theme or in custom themes

### ISSUE THREAD

**Issue by dermdaly** [SAP/gigya-nSS#14]
Steps to Reproduce
1. Create a new Native Screen set with minimal components in the NSS UI Builder.
2. Edit the JSON and set a primary color on your theme
3. Add a submit button to your minimal screen.
4. Run up a preview
5. Observe that the submit button's colour matches your primary color in your theme
<img width="432" alt="image" src="https://github.com/SAP/gigya-nSS/assets/259802/82345e80-7617-409b-a5f2-cbb200919dbc">

6. Run up an iOS app and load your minimal example.
7. Observe the submit button is in flutter's default "blue" 

![image](https://github.com/SAP/gigya-nSS/assets/259802/e4928227-65bf-4b7c-83ee-577ee6394192)

*Expected Result*
The button color should honour the theme at run time
*Actual Result* 
The button's color does not match the theme at run time

**Furthermore:**
8. Create a custom theme and add it to the JSON.
9. Set a primaryColour in the theme, and change the font size.
10. Apply the theme to the button
11. Observe that other themes items are applied (e.g. font size), but the color remains "flutter blue"

**Comment by tal-mi** [comment]
Please attach markup JSON.
On the current build, submit does honor theme colors.
