### ISSUE TITLE
Cannot update to version 1.8.0

### ISSUE THREAD

**Issue by cartera-anpost** [SAP/gigya-nSS#17]
Updated the dependencies to include Gigya NSS 1.8.0, however this then causes me a run time error when I attempt to load the screen.  The Gigya Core throws a run time error stating:

"Fatal error: [Gigya]: Gigya instance was originally created with a different GigyaAccountProtocol: GigyaAccount”

**Comment by sagishm** [comment]
Hi,
To provide resolution for this issue a SAP incident is required.
Please use the following link to open a support incident:

https://developers.gigya.com/display/GD/Opening+A+Support+Incident
Thanks,
Sagi
