### ISSUE TITLE
Textfields ignore border styling on iOS when Platform Awareness is enabled

### ISSUE THREAD

**Issue by AJScanlan** [SAP/gigya-nSS#19]
On iOS using nSS SDK 1.8.0 the border styling is not being applied to textfields when Platform Awareness is enabled

![Simulator Screenshot - iPhone 14 Pro - 2023-07-12 at 12 00 19](https://github.com/SAP/gigya-nSS/assets/11424393/5360a356-90af-47a1-90ef-7250ac9cd28e)
<img width="629" alt="Screenshot 2023-07-12 at 12 00 01" src="https://github.com/SAP/gigya-nSS/assets/11424393/18a98a05-197e-4b08-8021-f6cbe7b81339">
<img width="1039" alt="Screenshot 2023-07-12 at 11 57 50" src="https://github.com/SAP/gigya-nSS/assets/11424393/b908d9b3-6b10-4612-94e6-7cfa34eba788">

**Comment by tal-mi** [comment]
Hi,
See: https://github.com/SAP/gigya-nSS/blob/main/docs/COMPONENTS.md#component-type-textinput
Currently, Cupertino style inputs do not support borders. We intend to add it in the future.
