### ISSUE TITLE
Cannot build for Debug on Device since 1.7.1

### ISSUE THREAD

**Issue by dermdaly** [SAP/gigya-nSS#20]
Since the release of 1.7.1 debug builds are not possible on iOS when targeting a device.

this is caused by the fact the the debug build of the NSS Library embeds the Flutter Run time.
Since 1.7.1, this only includes the flutter run time slice for iOS-arm64_x86_64-simulator, and is missing iOS-arm64_armv7

Prior to 1.7.1, the embedded flutter run time included both slices

Now, if you use the latest version (or any version after 1.7.1), and compile for debug targeting a device (as opposed to a simulator), the compile fails as the import of Flutter fails.

the workaround is to use the GigyaNSSRelease cocoapod.

**Comment by dermdaly** [comment]
Confirmed this is still an issue in 1.9.0

**Comment by tal-mi** [comment]
Hi,

This is a known Flutter bug related to the Add to App feature.
Please note the following [known issue](https://github.com/SAP/gigya-nSS#known-issues-1).

Some Flutter versions fixed the issue but it has re-surfaced again.
If it will be completely resolved we will update accodingly.
