### ISSUE TITLE
Following an internal link can lead to a timeout awaiting callback from native code on iOS

### ISSUE THREAD

**Issue by dermdaly** [SAP/gigya-nSS#26]
**Steps to reproduce**
1. Create a screen set with two screens.  Let's call them "login" and "more-details"
2. In the login screen, include a label which is a an internal link.  Give it a value to link it to more details.  something like `"[Learn More](more-details)"`
3. When you tap on the "more details" label on iOS, observe it takes 30 seconds for the more details screen to show.

I believe the route cause of this is:

1. When the user taps on the link, the following is shown in the iOS console:
`flutter: initiateNextAction: for next screen id = about-profiling and action = none`

2. This leads to calling initiateAction in screen_service.dart, which invokes a native method.
3. Which fails (more on this below).
4. So it doesn't return
5. And the .timeout clause in initiateAction eventually gets called and ensures the flow can continue (i.e. after 30 seconds).

**Underlying cause**
When it calls back to the native NSS swift code the relevant method handler is called.  See line 69 of NativeScreenSetsViewModel.
This retrieves flowId as "none" and attempted to create an NssAction enum, passing "none"
None is not a valid enum - actually "unknown" is.  the fix may be to improve the NssAction enum init to create a unknown if the passed value is not one of the expected values.
This creation of the enum fails, which presumably throws a run time error.
the relevant lines to invoke the flowManager don't get triggered.

**Comment by dermdaly** [comment]
Note, setting an action to any of the other values seems to solve the symptom.  Effectively, telling the screen it's action is "otp" or "login" will fix it.  But it feels like I'm just masking a bug then.

**Comment by tal-mi** [comment]
Hi,
A screen action is not optional. "none" option is set to be removed.
This is an internal issue that we are going to handle soon.
In any case, always add a screen action to a screen as it is mandatory.

**Comment by dermdaly** [comment]
I'd suggest that this bug not be closed out, as it causes an exception to be thrown in the swift code.  If there's an underlying code fix, great, but otherwise, the bug is still present.
