### ISSUE TITLE
GigyaNSS does not release memory - Need best practise for loading screens.

### ISSUE THREAD

**Issue by dermdaly** [SAP/gigya-nSS#30]
We've found that running an app which loads NSS screens has constantly growing memory.
Steps to reproduce
1. Add NSS to your app
2. Launch the app and monitor the memory usage
3. Trigger loading of a NSS screen using GigyaNSS.shared.load (as per documentation)
4. See memory jump by about 100MB
5. Dismiss screen
6. Observe that the memory is not returned.
7. Launch the screen again
8. See memory jump by about 100 MB

We've tried grabbing a handle to the flutter engine, and calling destroyContext before re-loading, but this causes crashes. (that was a long shot).

There's nothing in the documentation on best practises, but I'm wondering if the programmer is expected to cache the value of GigyaNSS.Shared.load somehow and not call it multiple times.

**Comment by tal-mi** [comment]
Fixed in latest release.
