### ISSUE TITLE
V 1.9.2 Will not build on simulator - missing embedded framework.

### ISSUE THREAD

**Issue by dermdaly** [SAP/gigya-nSS#37]
### Checklist

- [X] The issue can be reproduced in the attached sample application in the repository.
- [X] I have read the relevant [SDK documentation](https://sap.github.io/gigya-nSS/) and have not found a suitable solution or answer.
- [X] I agree to the terms within the [SAP Code of Conduct](https://github.com/SAP/gigya-nSS/blob/main/CODE_OF_CONDUCT.md#code-of-conduct).

### Description

After upgrading from 1.9.1 to 1.9.2 the simulator builds no long work.  We've tracked this down to a missing embedded framework in the release.

### Reproduction

Steps to reproduce
1. Add GigyaNSS to your pod file.
2. Run pod install
3. Observe that 1.9.2 is installed.
4. Compile your project for simulator
5. Observe the following error:

```
building file list ... rsync: link_stat "/path/to/projectname/Pods/GigyaNss/GigyaNss/Flutter/Debug/App.xcframework/ios-arm64_x86_64-simulator//*" failed: No such file or directory (2)
done

sent 29 bytes  received 20 bytes  98.00 bytes/sec
total size is 0  speedup is 0.00
rsync error: some files could not be transferred (code 23) at /AppleInternal/Library/BuildRoots/0032d1ee-80fd-11ee-8227-6aecfccc70fe/Library/Caches/com.apple.xbs/Sources/rsync/rsync/main.c(996) [sender=2.6.9]
Command PhaseScriptExecution failed with a nonzero exit code

```
(Note: I've altered the directory names in the above for privacy reasons.)

7. Go back to podfile and set the version of GigyaNSS to 1.9.1, and retry
8. Observe that the project builds.

### Additional context

Upon further investigation, when we download the source from GitHub, we notice that in 1.9.1 the embedded framework directory App.framework has a `[ios-arm64_x86_64-simulator/App.framework` (see https://github.com/SAP/gigya-swift-sdk/tree/nss/v1.9.1/GigyaNss/Flutter/Debug/App.xcframework), yet in 1.9.2, the App.framework only contains an info.plist file, and no framework:
(see https://github.com/SAP/gigya-swift-sdk/tree/nss/v1.9.2/GigyaNss/Flutter/Debug/App.xcframework).

### SDK version

1.9.2

### Android/iOS

iOS

**Comment by sagishm** [comment]
Hi,
fixed on 1.9.3.
thanks for report.
